package by.epam.pronovich.controller.command;

public enum CommandName {
    WRONG_REQUEST,
    LOGOUT,
    USER_CHANGE_INFO_FORM,
    SAVE_USER_CHANGES,
    ADD_PRODUCT_FORM,
    CHANGE_PRODUCT_INFO_FORM,
    SAVE_PRODUCT_CHANGES,
    ADD_PRODUCT,
    AUTHENTICATION,
    REGISTRATION,
    REVIEW_FORM,
    ADD_REVIEW,
    CATALOG,
    REVIEW,
    PRODUCTINFO,
    OLENER,
    PRODUCT,
    LOKALIZATION,
    HISTORY,
    ADD_TO_BASKET,
    DELETE_FROM_BASKET,
    CHECKOUT,
    UPDATE_STATUS,
    SHOW_ORDERS,
    SEARCH
}
